# -*- coding: utf-8 -*-
"""Processing_Analysis_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12e87xF7nPhIRE-JR4zAcNaWR88Yutv9Q

This colab functions as a library with functions used in other data processing colabs. The functions are imported in and used so that we don't need duplicate code.

If you modify functions in this colab and use them in another colab, you must disconnect and delete the runtime of the other colab and then rerun that colab to see the updates. For this reason, I would suggest developing/testing new functions in other colabs and then moving them here once they're largely finalized.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
import re

def testimport():
  print('hello')

fig_save_path = '/content/drive/MyDrive/GPC/GPC_Web/Web_Data/Web_Crawler/Processing_Analysis_Data/figures/'

def process_sheet(sheet_name, last_row, sh):
  advertising = sh.worksheet(sheet_name)
  # get_all_values gives a list of rows.
  advertising_rows = advertising.get_all_values()

  # Convert to a DataFrame and render.
  # validation_set = pd.DataFrame.from_records(rows[1:101])
  advertising_df = pd.DataFrame.from_records(advertising_rows[1:last_row])
  advertising_df.columns = advertising_rows[0]
  return advertising_df

fontsize=12

# format scientific labels:
def format_labels(label):
  # round the number, then add K (3429 -> 3K);
  # if it's less than 1,000, just return the number
  # if it's more than 1,000,000, round to nearest million and add M
  if label < 1000:
    return label
  elif label >= 1000 and label < 1000000:
    return str(round(label, -3))[:-3]+'K'
  else:
    return str(round(label, -6))[:-6]+'M'

"""Putting Crawl data files into this colab notebook:
------------------
------------------

either you can drag and drop files in from Crawl_Data inside Processing Analysis Data or you can mount the Google drive and copy the whole Crawl_Data folder in.
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!cp -r '/content/drive/MyDrive/GPC/GPC_Web/Web_Data/Web_Crawler/Processing_Analysis_Data/Crawl_Data' .
!cp -r '/content/drive/MyDrive/GPC/GPC_Web/Web_Data/Web_Crawler/Processing_Analysis_Data/cmp_api_python' . # handles decoding of GPP strings
!git clone https://github.com/privacy-tech-lab/gpc-web-crawler.git

import sys
sys.path.append('/content/gpc-web-crawler/cmp_api_python')

from cmp_api import cmpapi_test  # This works now
c = cmpapi_test.CmpApi()

"""when merging dfs, the decoded gpp strings must be cast as strings. If they are dictionaries, the merging will fail. These functions convert columns to strings (cast_as_string) and back to dictionary (or whatever other type)"""

def cast_as_string(df, columns):
  for col in columns:
    df[col] = df[col].astype(str)
  return df

import ast

def apply_eval(df, columns):
    for col in columns:
        df[col] = df[col].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
    return df

def hist(lst):
  h = {}
  for l in lst:
    if l in h:
      h[l] += 1
    else:
      h[l] = 1
  return h

"""GPP decoding -- use the cmp_api_python library"""

# this function does the decoding
def decode_gpp_str(row, column):
  #check for null vals
  if pd.isnull(row[column]) == False:
    return cmpapi_test.decode(row[column], c)
  else:
    return None

"""example decoding"""

# cmpapi_python_example_data = {'site': ['1', '2', '3', '4'],
#         'gpp_string': [
#             #'DBABMA~CPxoFsAPxoFsAPoABABGCyCAAAAAAAAAAAAAAAAAAAAA.QAAA.IAAA',
#             #'DBABDA~BPxoFsAPxoFsAPoABABGCyCAAAAAAAAAAAAAAAAA.YAAAAAAAAAA',
#             #'DBABTA~1---',
#             #'DBABLA~BAAAAAAAAAA.QA',
#             #'DBABBg~BAAAAAAA.QA',
#             #None
#             'DBABBg~BUoAAAA',
#             'DBABzw~1YNY~BVQqAAAAAgA',
#             'DBABzw~1YNY~BVQqAAAAAgI',
#             'DBABzw~1YYY~BVQVAAAAAgI'
#       ]}
# cmpapi_python_example_df = pd.DataFrame(cmpapi_python_example_data)
# cmpapi_python_example_df['decoded'] = cmpapi_python_example_df.apply(decode_gpp_str, column='gpp_string', axis=1)
# cmpapi_python_example_df

"""Processing crawl data/ dealing with redo sites
-----

importing the data-- input
1. json file of error sites
2. csv of sites
3. json or csv of analysis data
"""

# helper function to strip 'www.' only
def remove_www(domain):
    domain = domain.replace('https://', '').replace('http://', '').strip('/')
    if domain.startswith('www.'):
        domain = domain[4:]
    return domain

def import_data(error_file, sites_file, analysis_file, folder):
    """
    Imports and processes site analysis data from JSON and CSV files.
    Handles missing domains using an optional crawl set file.
    """
    with open(error_file) as json_file:
        not_crawlable = json.load(json_file)

    if analysis_file.endswith('.csv'):
        df = pd.read_csv(analysis_file)
    else:
        df = pd.read_json(analysis_file)

    # Ensure all necessary columns exist before performing operations.
    required_cols = ['uspapi_before_gpc', 'usp_cookies_before_gpc', 'uspapi_after_gpc', 'usp_cookies_after_gpc', 'gpp_before_gpc', 'gpp_after_gpc', 'site_id', 'domain']
    for col in required_cols:
        if col not in df.columns:
            df[col] = np.nan

    # Prioritize uspapi over cookies
    df['usps_before_gpc'] = np.where(pd.isna(df['uspapi_before_gpc']), df['usp_cookies_before_gpc'], df['uspapi_before_gpc'])
    df['usps_after_gpc'] = np.where(pd.isna(df['uspapi_after_gpc']), df['usp_cookies_after_gpc'], df['uspapi_after_gpc'])

    # Decode GPP strings
    df['decoded_gpp_before_gpc'] = df.apply(decode_gpp_str, column='gpp_before_gpc', axis=1)
    df['decoded_gpp_after_gpc'] = df.apply(decode_gpp_str, column='gpp_after_gpc', axis=1)

    # Pre-calculate boolean series for robustness
    has_uspapi_before = pd.notna(df['uspapi_before_gpc'])
    has_usp_cookies_before = pd.notna(df['usp_cookies_before_gpc'])
    has_uspapi_after = pd.notna(df['uspapi_after_gpc'])
    has_usp_cookies_after = pd.notna(df['usp_cookies_after_gpc'])

    # Define the conditions for np.select using the pre-calculated booleans
    conditions = [
        # Both: Check for non-null values in both API and cookie columns (before and after)
        ((has_uspapi_before | has_usp_cookies_before) & (has_uspapi_after | has_usp_cookies_after)),
        # Neither: All four columns are null
        ((~has_uspapi_before) & (~has_usp_cookies_before) & (~has_uspapi_after) & (~has_usp_cookies_after)),
        # USPAPI only: Check for a non-null USPAPI value and null cookie values
        (((has_uspapi_before) | (has_uspapi_after)) & (~has_usp_cookies_before) & (~has_usp_cookies_after)),
        # Cookies only: Check for a non-null cookie value and null USPAPI values
        (((has_usp_cookies_before) | (has_usp_cookies_after)) & (~has_uspapi_before) & (~has_uspapi_after))
    ]

    replacements = ['both', 'neither', 'uspapi', 'cookies']
    df['USPS implementation'] = np.select(conditions, replacements, default=None).astype(str)

    # The rest of the code for site status
    df_sites = pd.read_csv(sites_file)
    df_sites['domain'] = df_sites['Site URL'].replace(to_replace=r'https://', value='', regex=True)
    df_sites['site_id'] = df_sites.index

    # Load crawl set file if folder is specified and fill in missing domains
    if folder:
        crawl_set_path = f'/content/drive/MyDrive/GPC/GPC_Web/Web_Data/Web_Crawler/Crawl_Set_Batches/crawl-set-{folder}.csv'
        try:
            df_crawl_set = pd.read_csv(crawl_set_path)
            # Assuming the crawl set file also has 'site_id' and 'Site URL'
            df_crawl_set['site_id'] = df_crawl_set.index
            df_crawl_set['domain_from_crawl_set'] = df_crawl_set['Site URL'].replace(to_replace=r'https://', value='', regex=True)

            # Merge to get domains from crawl set where domain is null in df
            df = pd.merge(df, df_crawl_set[['site_id', 'domain_from_crawl_set']], on='site_id', how='left')
            df['domain'] = np.where(pd.isnull(df['domain']), df['domain_from_crawl_set'], df['domain'])
            df = df.drop(columns=['domain_from_crawl_set'])
        except FileNotFoundError:
            print(f"Crawl set file not found at: {crawl_set_path}")
        except KeyError as e:
            print(f"Missing expected column in crawl set file: {e}")


    added = df_sites.loc[df_sites['site_id'].isin(df['site_id'])].reset_index(drop=True)

    """
    added['domain_wwwfree'] = added['domain'].str.strip('/')
    added.loc[added['domain_wwwfree'].str.startswith('www.'), 'domain_wwwfree'] = \
        added.loc[added['domain_wwwfree'].str.startswith('www.'), 'domain_wwwfree'].str[4:]

    df['domain_wwwfree'] = df['domain'].str.strip('/')
    df.loc[df['domain_wwwfree'].str.startswith('www.'), 'domain_wwwfree'] = \
        df.loc[df['domain_wwwfree'].str.startswith('www.'), 'domain_wwwfree'].str[4:]

    merged_domains = pd.merge(
        df[['site_id', 'domain_wwwfree']],
        added[['site_id', 'domain_wwwfree']],
        on='site_id',
        suffixes=('_df', '_sites'),
        how='inner'
    )

    merged_domains['status'] = np.where(
        merged_domains['domain_wwwfree_df'] != merged_domains['domain_wwwfree_sites'],
        'redirected',
        'added'
    )

    added = pd.merge(added, merged_domains[['site_id', 'status']], on='site_id', how='left')

    added = added.drop(columns=['Site URL', 'domain', 'domain_wwwfree'])

    df_sites = pd.merge(df_sites, added, how='outer', on='site_id')

    df_sites['status'] = df_sites['status'].fillna('not added')

    return not_crawlable, df, df_sites
    """

    for frame in [df, added]:
        frame['domain_wwwfree'] = frame['domain'].str.strip('/').str.replace(r'^www\.', '', regex=True)

    merged_domains = pd.merge(
        df[['site_id', 'domain_wwwfree']],
        added[['site_id', 'domain_wwwfree']],
        on='site_id',
        suffixes=('_df', '_sites'),
        how='inner'
    )

    merged_domains['status'] = np.where(
        merged_domains['domain_wwwfree_df'] != merged_domains['domain_wwwfree_sites'],
        'redirected',
        'added'
    )

    added = pd.merge(added, merged_domains[['site_id', 'status']], on='site_id', how='left')

    # --- THE FIX IS HERE ---
    # Drop from 'added'
    added = added.drop(columns=['Site URL', 'domain', 'domain_wwwfree'], errors='ignore')
    # Drop from 'df' (This is the one that was leaking!)
    df = df.drop(columns=['domain_wwwfree'], errors='ignore')
    # -----------------------

    df_sites = pd.merge(df_sites, added, how='outer', on='site_id')
    df_sites['status'] = df_sites['status'].fillna('not added')

    return not_crawlable, df, df_sites

def make_full_df(df, df_sites):
  df_sites = df_sites.drop(columns=['domain'])
  df = df.drop(columns=['id'])
  merged = pd.merge(df_sites, df, how = 'outer', on ='site_id')
  return merged

def error_origins(err, full_not_crawlable, full_merged_df):
  series = pd.Series(full_not_crawlable[err]).drop_duplicates()
  print("number of unique sites with " + err + ":", len(series))
  err_df = full_merged_df[full_merged_df['domain'].isin(series)]
  print("number of sites with " + err + " that were still analyzed:",len(err_df))
  print("number of sites with " + err + " that were not analyzed:", len(series)-len(err_df))

def remove_error_sites(df, not_crawlable):
  # any sites that are not crawlable we want to ignore
  total_nc = []
  exclude_keys = ["TimeoutError", 'singleTimeoutError']
  for key in not_crawlable.keys():
    if key not in exclude_keys:
      total_nc += not_crawlable[key]
  not_crawlable_df = df[df['Site URL'].isin(total_nc)]
  # temp = [x for x in total_nc if x not in set(list(not_crawlable_df['Site URL']))]
  df1 = df.drop(not_crawlable_df.index, inplace = False)

  # df.drop(not_crawlable_df, inplace=True) #--- if we want to exclude error sites in our analysis, have this line instead and return df
  # print("df",len(df))
  return df1, exclude_keys

def success_rate(df, df_sites, not_crawlable):
  print("Success rate:")
  df_no_error, exclude_keys = remove_error_sites(df,not_crawlable)
  return (str(len(df_no_error))+' / '+str(len(df_sites))+' = ' + str(len(df_no_error)/len(df_sites))+ " (sites with the following errors not removed from analysis data: "+ str(exclude_keys)+ ")")

"""urlClassification 3rd party processing
-----
"""

def count_third_parties(row):
  # thirdPartyRow = row['urlClassification']['thirdParty']
  thirdPartyRow = row
  total_third_parties = 0
  for key in list(thirdPartyRow.keys()):
    total_third_parties += len(thirdPartyRow[key])
  return total_third_parties

def third_parties_urlClass(row):
  return row['urlClassification']['thirdParty']

def process_ad_network_string(row):
  return row['unique_ad_networks'].split(',')[:-1]
def number_unique_ad_networks(row):
  return len(row['unique_ad_networks'])

def return_top_n(d, n) :
   return {k: d[k] for k in list(d)[:n]}

def networks_in_row(row, site):
  # returns true if the network is in the row
  if site in row['unique_ad_networks']:
    return True
  else:
    return False

"""GPP Opt Outs/ GPP Sections function
------
"""

def sections_histogram_multisection(df, col)  :
  sections_hist = {'none':0}
  def extract_sections(row, column):
    decoded_gpp = row[column]
    if decoded_gpp is None or decoded_gpp == {}:
      if 'none' in sections_hist:
        sections_hist['none'] += 1
      else:
        sections_hist['none'] = 1
    else:
      s = str(list(decoded_gpp.keys()))
      if s in sections_hist:
        sections_hist[s] += 1
      else:
        sections_hist[s] = 1


  df.apply(extract_sections, column=col, axis=1)
  return (sections_hist)

def sections_histogram_single_section(df, col)  :
  sections_hist = {'none':0}
  def extract_sections(row, column):
    decoded_gpp = row[column]
    if decoded_gpp is None or decoded_gpp == {}:
      if 'none' in sections_hist:
        sections_hist['none'] += 1
      else:
        sections_hist['none'] = 1
    else:
      s = list(decoded_gpp.keys())

      for i in s:
        if i in sections_hist:
          sections_hist[i] += 1
        else:
          sections_hist[i] = 1


  df.apply(extract_sections, column=col, axis=1)

  return (sections_hist)

def sections_table(df)  :
  sections_df = df.copy()
  # make sure all drop columns exist before dropping. start w a potential list of cols to drop, as they're unnecessary in this calculation.
  possible_drop_cols = ['uspapi_before_gpc', 'uspapi_after_gpc', 'usp_cookies_before_gpc', 'usp_cookies_after_gpc',
                                          'usps_before_gpc', 'usps_after_gpc','OptanonConsent_after_gpc', 'OptanonConsent_before_gpc',
                                          'USPS implementation']
  drop_cols = []
  for col in possible_drop_cols:
    if col in sections_df.columns: # check if each col exists; if it does, add it to cols to drop
      drop_cols.append(col)
  sections_df = sections_df.drop(columns=drop_cols)
  # we want the decoded gpp columns to be evaluated as a dictionary so that we can access attributes. We don't know what type it's coming in as (i.e. string or dict)
  # if it's already a dict, apply_eval throws an error. So, cast as string and then eval so that it can come in as either.
  sections_df = cast_as_string(sections_df, ['decoded_gpp_before_gpc','decoded_gpp_after_gpc']) # make sure these are objects, not strings
  sections_df = apply_eval(sections_df, ['decoded_gpp_before_gpc','decoded_gpp_after_gpc']) # make sure these are objects, not strings
  # use lambda functions to parse the dict data: order is SaleOptOut, SharingOptOut, TargetedAdvertisingOptOut, Gpc (with commas)
  # for parsing purposes, if one of these cols doesn't exist for a section, the comma is still added. The GPC flag is just binary
  for time in ['before', 'after']:
    # nat has all 3
    sections_df['usnatv1_'+time] = sections_df.apply(lambda row:  str(int(row['decoded_gpp_'+time+'_gpc']['usnatv1']['SaleOptOut']))+','+str(int(row['decoded_gpp_'+time+'_gpc']['usnatv1']['SharingOptOut']))+','+str(int(row['decoded_gpp_'+time+'_gpc']['usnatv1']['TargetedAdvertisingOptOut']))+','+str(int(row['decoded_gpp_'+time+'_gpc']['usnatv1']['Gpc'])) if (row['decoded_gpp_'+time+'_gpc'] is not None and 'usnatv1' in row['decoded_gpp_'+time+'_gpc']) else None , axis=1)
    # CA has sale + sharing
    sections_df['uscav1_'+time] = sections_df.apply(lambda row:  str(int(row['decoded_gpp_'+time+'_gpc']['uscav1']['SaleOptOut']))+','+str(int(row['decoded_gpp_'+time+'_gpc']['uscav1']['SharingOptOut']))+','+','+str(int(row['decoded_gpp_'+time+'_gpc']['uscav1']['Gpc'])) if (row['decoded_gpp_'+time+'_gpc'] is not None and 'uscav1' in row['decoded_gpp_'+time+'_gpc']) else None , axis=1)
    # these all have Sale and Targeted Advertising
    for sect in [ 'uscov1', 'usctv1']: # have GPC flag
      sections_df[sect+'_'+time] = sections_df.apply(lambda row:  str(int(row['decoded_gpp_'+time+'_gpc'][sect]['SaleOptOut']))+','+','+str(int(row['decoded_gpp_'+time+'_gpc'][sect]['TargetedAdvertisingOptOut']))+','+str(int(row['decoded_gpp_'+time+'_gpc'][sect]['Gpc'])) if (row['decoded_gpp_'+time+'_gpc'] is not None and sect in row['decoded_gpp_'+time+'_gpc']) else None , axis=1)
    for sect in ['usvav1', 'usutv1']: # don't have GPC flag
      sections_df[sect+'_'+time] = sections_df.apply(lambda row:  str(int(row['decoded_gpp_'+time+'_gpc'][sect]['SaleOptOut']))+','+','+str(int(row['decoded_gpp_'+time+'_gpc'][sect]['TargetedAdvertisingOptOut']))+',' if (row['decoded_gpp_'+time+'_gpc'] is not None and sect in row['decoded_gpp_'+time+'_gpc']) else None , axis=1)

  return sections_df

"""The pie chart is difficult to view if all the smallest values are next to each other (because the labels overlap). To combat this, we will order the data [max, min, 2nd highest, 2nd lowest,....]."""

def order_data_for_pie_chart(data):
  data_sorted = {k: v for k, v in sorted(data.items(), key=lambda item: item[1])}
  data_keys = list(data_sorted.keys())
  ordered_keys = []
  ordered_values = []
  while len(data_keys) > 0:
    if len(data_keys) % 2 == 0:
      last = data_keys.pop(len(data_keys)-1)
      ordered_keys.append(last)
      ordered_values.append(data_sorted[last])
    else:
      first = data_keys.pop(0)
      ordered_keys.append(first)
      ordered_values.append(data_sorted[first])

  return ordered_keys, ordered_values

"""have some default colors so they match month to month -- this only applies to the pie charts, which we no longer use"""

def get_colors(data_keys):
  colors = {'usnatv1': 'tab:red', 'uspv1': 'tab:blue', 'uscav1': 'gold', 'tcfcav1': 'tab:gray', 'none': 'tab:brown', 'tcfeuv2': 'tab:pink'}
  output_colors = [None for i in data_keys]
  extras = ['lightsteelblue','tab:cyan', 'tab:olive', 'palegoldenrod']
  for i in range(len(data_keys)):
    # get rid of quotes, []; this is to check if it's a single entry in the list
    old_key = data_keys[i]
    new_key = old_key.replace("'",'')
    new_key = new_key.replace("[",'')
    new_key = new_key.replace("]",'')
    if new_key in colors:
      output_colors[i] = colors[new_key]
    else:
      if 'usnatv1' in data_keys[i] and 'uspv1' in data_keys[i]:
        output_colors[i] = 'tab:purple'
      elif 'uscav1' in data_keys[i] and 'uspv1' in data_keys[i]:
        output_colors[i] = 'tab:green'
      elif 'tcfcav1' in data_keys[i] and 'tcfeuv2' in data_keys[i]:
        output_colors[i] = 'tab:orange'
      else:
        output_colors[i] = extras.pop(0)
  return output_colors

"""plot the sections in a pie chart. we no longer use this"""

def plot_sections(data, move_list, time):
  # move list is a list of tuples of the autotext to move and where to move it (ie (5, 'top') moves the 5th autotext to the top
  #input histogram of sections + frequencies made by sections_histogram function
  ind = np.arange(1)
  width = 0.6
  data_keys, data_values = order_data_for_pie_chart(data)

  #just for formatting-- change as necessary
  for val in range(len(data_keys)):
    if ',' in data_keys[val]:
      idx = data_keys[val].find(',')
      data_keys[val] = data_keys[val][:idx+1] + '\n' + data_keys[val][idx+1:]
  # summing all values b/c sum() isn't working on lists
  total = 0
  for i in data_values:
    total += i
  total1 = format(total, ',d') # for formatting purposes, need to pass str with commas
  #actually do the plotting
  c = get_colors(data_keys)
  # print(c)
  fig, ax = plt.subplots()
  wedges, texts, autotexts = ax.pie(data_values, labels=data_keys, colors = c,
         textprops={'fontsize': 10.5},
         pctdistance = .7,
         autopct=lambda p: '{:,.0f}/{t}'.format(p * total / 100, t=total1)
         )

  # Move a label
  for idx, loc in move_list:
    autotexts[idx]._verticalalignment= loc
  # https://stackoverflow.com/questions/23577505/how-to-avoid-overlapping-of-labels-autopct-in-a-pie-chart
  ############
  # format(p * total / 100, ',d')
  # fmt='{:,.0f}'

  # to put the data in a legend instead of on the chart
  # labs = []
  # for i in autotexts:
  #   labs.append(i.get_text())
  # labels = list(zip(data_keys, labs))
  # ax.legend(bbox_to_anchor=(0.85, 1), loc='upper left', labels=labels)
  plt.title('Sections implemented in GPP strings ('+time+')',fontsize=14)

  # plt.show()
  return fig

"""a function that outputs both the multi section and single section pie charts"""

def make_sections_pie_charts(df, save, time):
  # filter for sites with gpp before or after
  df_gpp = df[(pd.isnull(df['gpp_before_gpc']) == False) | (pd.isnull(df['gpp_after_gpc']) == False)]
  sh = sections_histogram_multisection(df_gpp,'decoded_gpp_before_gpc')
  fig_multi = plot_sections(sh, [(5,'bottom')], time)
  print('')
  sh1 = sections_histogram_single_section(df_gpp,'decoded_gpp_before_gpc')
  fig_single = plot_sections(sh1,[], time)
  if save == True:
    fig_multi.savefig(fig_save_path + 'gpp_sections_' + time.replace(' ', '_').replace('/', '_') + '.png', dpi=100, bbox_inches='tight')
    fig_single.savefig(fig_save_path + 'gpp_sections_single_' + time.replace(' ', '_').replace('/', '_') + '.png', dpi=100, bbox_inches='tight')

"""determine how many sites have sale/sharing/targeted advertising have values 0,1,2 with regex"""

def sections_analysis(df):
  table = pd.DataFrame()
  table.index = ['Positive Instance Counts']
  table['Sale = 0 Before'] = [0]
  table['Sale = 1 Before'] = [0]
  table['Sale = 2 Before'] = [0]
  table['Sharing = 0 Before'] = [0]
  table['Sharing = 1 Before'] = [0]
  table['Sharing = 2 Before'] = [0]
  table['TargetedAdvertising = 0 Before'] = [0]
  table['TargetedAdvertising = 1 Before'] = [0]
  table['TargetedAdvertising = 2 Before'] = [0]
  table['Sale = 0 After'] = [0]
  table['Sale = 1 After'] = [0]
  table['Sale = 2 After'] = [0]
  table['Sharing = 0 After'] = [0]
  table['Sharing = 1 After'] = [0]
  table['Sharing = 2 After'] = [0]
  table['TargetedAdvertising = 0 After'] = [0]
  table['TargetedAdvertising = 1 After'] = [0]
  table['TargetedAdvertising = 2 After'] = [0]
  table['Gpc = 0 Before'] = [0]
  table['Gpc = 1 Before'] = [0]
  table['Gpc = 0 After'] = [0]
  table['Gpc = 1 After'] = [0]

  for time in ['Before', 'After']:
    for sect in ['usnatv1', 'uscav1','uscov1', 'usvav1', 'usctv1', 'usutv1']:
      s = sect + '_'+ time.lower()
      table['Sale = 0 '+time] += len(df[((pd.isnull(df[s]) == False) & (df[s].str.contains(r'^0,[012]{0,1},[012]{0,1},[012]{0,1}$')))])
      table['Sale = 1 '+time] += len(df[((pd.isnull(df[s]) == False) & (df[s].str.contains(r'^1,[012]{0,1},[012]{0,1},[012]{0,1}$')))])
      table['Sale = 2 '+time] += len(df[((pd.isnull(df[s]) == False) & (df[s].str.contains(r'^2,[012]{0,1},[012]{0,1},[012]{0,1}$')))])
      table['Sharing = 0 '+time] += len(df[((pd.isnull(df[s]) == False) & (df[s].str.contains(r'^[012]{0,1},0,[012]{0,1},[012]{0,1}$')))])
      table['Sharing = 1 '+time] += len(df[((pd.isnull(df[s]) == False) & (df[s].str.contains(r'^[012]{0,1},1,[012]{0,1},[012]{0,1}$')))])
      table['Sharing = 2 '+time] += len(df[((pd.isnull(df[s]) == False) & (df[s].str.contains(r'^[012]{0,1},2,[012]{0,1},[012]{0,1}$')))])
      table['TargetedAdvertising = 0 '+time] += len(df[((pd.isnull(df[s]) == False) & (df[s].str.contains(r'^[012]{0,1},[012]{0,1},0,[012]{0,1}$')))])
      table['TargetedAdvertising = 1 '+time] += len(df[((pd.isnull(df[s]) == False) & (df[s].str.contains(r'^[012]{0,1},[012]{0,1},1,[012]{0,1}$')))])
      table['TargetedAdvertising = 2 '+time] += len(df[((pd.isnull(df[s]) == False) & (df[s].str.contains(r'^[012]{0,1},[012]{0,1},2,[012]{0,1}$')))])
      table['Gpc = 0 '+time] += len(df[((pd.isnull(df[s]) == False) & (df[s].str.contains(r'^[012]{0,1},[012]{0,1},[012]{0,1},0$')))])
      table['Gpc = 1 '+time] += len(df[((pd.isnull(df[s]) == False) & (df[s].str.contains(r'^[012]{0,1},[012]{0,1},[012]{0,1},1$')))])


  return table

def plot_barh_chart_gpp(table, labels, colors, title, col, time):

  # get the data to plot
  na, opt_out, not_opt_out = ([table[col + ' = 0 After']['Positive Instance Counts'], table[col + ' = 0 Before']['Positive Instance Counts']],
                              [table[col + ' = 1 After']['Positive Instance Counts'], table[col + ' = 1 Before']['Positive Instance Counts']],
                              [table[col + ' = 2 After']['Positive Instance Counts'], table[col + ' = 2 Before']['Positive Instance Counts']])
  ind = np.arange(2)
  width = 0.6

  fig, ax = plt.subplots(figsize =(8, 2.5))
  # plot the bars
  left = np.zeros(2)
  data = [na, not_opt_out, opt_out]
  i = 0
  for bar in range(len(data)):
    p = ax.barh(ind, data[bar], width, left = left, color=colors[bar])
    left += data[i]
    # ax.bar_label(p, padding=2, label_type='center', fmt='{:,.0f}',fontsize=10.5) #
    i += 1
  # set titles/axes

    ######
  # set titles/axes/labels
  y_placement = []
  for i in range(len(data)):
    pos1= 0.22 + i
    pos2 = 0.5 + i
    pos3 = i
    y_placement.append([pos1,pos2, pos3])
  data_by_bar = [[i[x] for i in data] for x in range(len(data[0]))]
  n = max([sum(x) for x in data_by_bar])
  ax.set_xlim(right=ax.get_xlim()[1]+(n*.02), auto=False)
  ax.margins(0, .23)
  for month in ind:
    x_placement = []

    for idx in range(len(data_by_bar[month])):
      frac = .08 # if a bar is less than this fraction of total, we want to use an arrow to point and label that way
      if data_by_bar[month][idx] < frac*n:
        label_placement = sum(data_by_bar[month][0:idx]) + 0.35*(data_by_bar[month][idx]) # since the arrows are tilted they're too far right. adjusted this by using .35 instead of.5
        if (len(x_placement) > 0) and (label_placement - x_placement[-1] < .05*n): # if labels are too close, move them over more to the right
          text_placement = label_placement + .05*n
        else:
          text_placement = label_placement
        ax.annotate(format(data_by_bar[month][idx], ',d') , xy=(label_placement, y_placement[month][0]), xytext=(text_placement, y_placement[month][1]), arrowprops=dict(facecolor='black', arrowstyle="->"),fontsize=11)
      else:
        label_placement = sum(data_by_bar[month][0:idx]) + 0.5*(data_by_bar[month][idx]) # put just text labels directly in the middle
        text_placement = label_placement
        ax.annotate(format(data_by_bar[month][idx], ',d'), xy=(label_placement, y_placement[month][2]), ha= 'center', va= 'center',fontsize=11)
      x_placement += [text_placement]
  #######

  plt.title(title +' ('+time+', n = '+format(n, ',d')+')', pad = 30,fontsize=14)
  ax.set_yticks(ind)
  ax.set_yticklabels(labels,fontsize=10.5)
  plt.xticks(np.arange(0, n+100, 150),fontsize=10.5)
  # xlabels = [format(label, ',.0f') for label in ax.get_xticks()]
  xlabels = [format_labels(label) for label in ax.get_xticks()]
  ax.set_xticklabels(xlabels)
  fig.legend(('Not Applicable', 'Did Not Opt Out', 'Opted Out'), ncols=3, bbox_to_anchor=(.81, 1.03),fontsize=10.5)
  return fig

def plot_gpp_gpc_flag(table, labels, colors, title, col, time):

  # get the data to plot
  gpc_0, gpc_1 = ([table[col + ' = 0 After']['Positive Instance Counts'], table[col + ' = 0 Before']['Positive Instance Counts']],
                              [table[col + ' = 1 After']['Positive Instance Counts'], table[col + ' = 1 Before']['Positive Instance Counts']])
  ind = np.arange(2)
  width = 0.6

  fig, ax = plt.subplots(figsize =(8, 2.5))
  # plot the bars
  left = np.zeros(2)
  data = [gpc_0, gpc_1]
  i = 0
  for bar in range(len(data)):
    p = ax.barh(ind, data[bar], width, left = left, color=colors[bar])
    left += data[i]
    i += 1
  # set titles/axes


  ######
  # set titles/axes/labels
  y_placement = []
  for i in range(len(data)):
    pos1= 0.22 + i
    pos2 = 0.5 + i
    pos3 = i
    y_placement.append([pos1,pos2, pos3])
  data_by_bar = [[i[x] for i in data] for x in range(len(data[0]))]
  n = max([sum(x) for x in data_by_bar])
  ax.set_xlim(right=ax.get_xlim()[1]+(n*.02), auto=False)
  ax.margins(None, .25)
  for month in ind:
    x_placement = []

    for idx in range(len(data_by_bar[month])):
      frac = .08 # if a bar is less than this fraction of total, we want to use an arrow to point and label that way
      if data_by_bar[month][idx] < frac*n:
        label_placement = sum(data_by_bar[month][0:idx]) + 0.35*(data_by_bar[month][idx]) # since the arrows are tilted they're too far right. adjusted this by using .35 instead of.5
        if (len(x_placement) > 0) and (label_placement - x_placement[-1] < .05*n): # if labels are too close, move them over more to the right
          text_placement = label_placement + .05*n
        else:
          text_placement = label_placement
        ax.annotate(format(data_by_bar[month][idx], ',d') , xy=(label_placement, y_placement[month][0]), xytext=(text_placement, y_placement[month][1]), arrowprops=dict(facecolor='black', arrowstyle="->"),fontsize=11)
      else:
        label_placement = sum(data_by_bar[month][0:idx]) + 0.5*(data_by_bar[month][idx]) # put just text labels directly in the middle
        text_placement = label_placement
        ax.annotate(format(data_by_bar[month][idx], ',d'), xy=(label_placement, y_placement[month][2]), ha= 'center', va= 'center',fontsize=11)
      x_placement += [text_placement]
  #######
  plt.title(title +' ('+time+', n = '+format(n, ',d')+')', pad = 30,fontsize=14)
  ax.set_yticks(ind)
  ax.set_yticklabels(labels,fontsize=10.5)
  plt.xticks(np.arange(0, n+100, 150),fontsize=10.5)
  # xlabels = [format(label, ',.0f') for label in ax.get_xticks()]
  xlabels = [format_labels(label) for label in ax.get_xticks()]
  ax.set_xticklabels(xlabels)
  fig.legend(( 'GPC = 0', 'GPC = 1'), ncols=3, bbox_to_anchor=(.66, 1.03),fontsize=10.5)
  return fig

def plot_gpp_opt_outs(df, save, time, colors_list):
  df_gpp = df[(pd.isnull(df['gpp_before_gpc']) == False) | (pd.isnull(df['gpp_after_gpc']) == False)]
  if len(df_gpp) == 0 :
    print('no gpp graphs because no gpp data in input dataframe')
  else:
    sections_table_df = sections_table(df_gpp)
    ta = sections_analysis(sections_table_df)
    fig_sale = plot_barh_chart_gpp(ta,
                        ['After\nGPC', 'Before\nGPC'],
                        colors_list,
                        'SaleOptOut','Sale', time)


    print('')
    fig_sharing = plot_barh_chart_gpp(ta,
                        ['After\nGPC', 'Before\nGPC'],
                        colors_list,
                        'SharingOptOut','Sharing', time)
    print('')
    fig_targeted_advertising = plot_barh_chart_gpp(ta,
                        ['After\nGPC', 'Before\nGPC'],
                        colors_list,
                        'TargetedAdvertisingOptOut','TargetedAdvertising', time)
    print('')
    fig_gpc = plot_gpp_gpc_flag(ta,
                        ['After\nGPC', 'Before\nGPC'],
                        colors_list[1:],
                        'GPC Sub-section','Gpc', time)
    if save == True:
     fig_sale.savefig(fig_save_path + time.replace(' ', '_').replace('/', '_') + '_sale_opt_out.png', dpi=100, bbox_inches='tight')
     fig_sharing.savefig(fig_save_path + time.replace(' ', '_').replace('/', '_') + '_sharing_opt_out.png', dpi=100, bbox_inches='tight')
     fig_targeted_advertising.savefig(fig_save_path + time.replace(' ', '_').replace('/', '_') + '_targeted_advertising_opt_out.png', dpi=100, bbox_inches='tight')
     fig_gpc.savefig(fig_save_path + time.replace(' ', '_').replace('/', '_') + '_gpc_flag.png', dpi=100, bbox_inches='tight')

"""OptanonConsent Cookie analysis
-----
"""

def get_OAC_sites_before(df):
  return df[(pd.isnull(df['OptanonConsent_before_gpc']) == False) ]
def get_OAC_sites_after(df):
  return df[(pd.isnull(df['OptanonConsent_after_gpc']) == False)]
def get_OAC_sites_before_values(df, time):

  return (df[(pd.isnull(df['OptanonConsent_'+time+'_gpc']) == False) & (df['OptanonConsent_'+time+'_gpc'] == 'isGpcEnabled=1')],
          df[(pd.isnull(df['OptanonConsent_'+time+'_gpc']) == False) & (df['OptanonConsent_'+time+'_gpc'] == 'isGpcEnabled=0')],
          df[(pd.isnull(df['OptanonConsent_'+time+'_gpc']) == False) & (df['OptanonConsent_'+time+'_gpc'] == 'no_gpc')])
#

def plot_barh_chart_OAC(df, colors, title, save, time):

  # get the data to plot
  opt_out_b, no_opt_out_b, no_gpc_b = get_OAC_sites_before_values(df,'before')
  opt_out_a, no_opt_out_a, no_gpc_a = get_OAC_sites_before_values(df,'after')

  # to get total number of sites with OAC, concat all then drop duplicates. This is necessary because # with OAC before and after may be different.
  n_title = len(pd.concat([opt_out_a, no_opt_out_a, no_gpc_a ,opt_out_b, no_opt_out_b, no_gpc_b]).drop(columns=[ 'decoded_gpp_before_gpc', 'decoded_gpp_after_gpc', 'unique_ad_networks']).drop_duplicates())

  na, opt_out, not_opt_out = ([len(no_gpc_a), len(no_gpc_b)],
                              [len(opt_out_a), len(opt_out_b)],
                              [len(no_opt_out_a), len(no_opt_out_b)])

  ind = np.arange(2)
  width = 0.6

  fig, ax = plt.subplots(figsize =(8, 2.5), dpi=100)

  # plot the bars
  left = np.zeros(2)
  data = [na, not_opt_out, opt_out]
  i = 0
  for bar in range(len(data)):
    p = ax.barh(ind, data[bar], width, left = left, color=colors[bar])
    left += data[i]
    # ax.bar_label(p, label_type='center', padding=1, fmt='{:,.0f}',fontsize=10.5)
    i += 1

#     ######
#   # set titles/axes/labels
  y_placement = []
  for i in range(len(data)):
    pos1= 0.22 + i
    pos2 = 0.5 + i
    pos3 = i
    y_placement.append([pos1,pos2, pos3])
  data_by_bar = [[i[x] for i in data] for x in range(len(data[0]))]
  n = max([sum(x) for x in data_by_bar])
  ax.set_xlim(right=ax.get_xlim()[1]+(n*.02), auto=False)
  ax.margins(0, .25)
  for month in ind:
    x_placement = []

    for idx in range(len(data_by_bar[month])):
      frac = .08 # if a bar is less than this fraction of total, we want to use an arrow to point and label that way
      if data_by_bar[month][idx] < frac*n:
        label_placement = sum(data_by_bar[month][0:idx]) + 0.35*(data_by_bar[month][idx]) # since the arrows are tilted they're too far right. adjusted this by using .35 instead of.5
        if (len(x_placement) > 0) and (label_placement - x_placement[-1] < .05*n): # if labels are too close, move them over more to the right
          text_placement = label_placement + .05*n
        else:
          text_placement = label_placement
        ax.annotate(format(data_by_bar[month][idx], ',d') , xy=(label_placement, y_placement[month][0]), xytext=(text_placement, y_placement[month][1]), arrowprops=dict(facecolor='black', arrowstyle="->"),fontsize=11)
      else:
        label_placement = sum(data_by_bar[month][0:idx]) + 0.5*(data_by_bar[month][idx]) # put just text labels directly in the middle
        text_placement = label_placement
        ax.annotate(format(data_by_bar[month][idx], ',d'), xy=(label_placement, y_placement[month][2]), ha= 'center', va= 'center',fontsize=11)
#       x_placement += [text_placement]
#   #######
  # set titles/axes
  plt.title(title +' ('+time+', n = '+format (n_title, ',d')+')', pad = 30,fontsize=14)
  ax.set_yticks(ind)
  ax.set_yticklabels(['After GPC', 'Before GPC'],fontsize=11)
  plt.xticks(np.arange(0, na[1]+not_opt_out[1]+opt_out[1] + 125, 250),fontsize=11)
  xlabels = [format(label, ',.0f') for label in ax.get_xticks()] # just add commas
  # xlabels = [format_labels(label) for label in ax.get_xticks()] # axis are 1K, 2K, etc, numbers are too small for this in this graph
  ax.set_xticklabels(xlabels)
  fig.legend(('Not Applicable', 'Did Not Opt Out', 'Opted Out'), ncols=3, bbox_to_anchor=(.81, 1.03),fontsize=10.5)
  if save == True:
    plt.savefig(fig_save_path + time.replace(' ', '_').replace('/', '_') + '_OAC_opt_outs.png', dpi=100, bbox_inches='tight') ###########
  plt.show()

"""USPS
-----

filters df based on neither, both, uspapi, cookies; used in making the table

create the table that was used for the paper analysis

since max # of cols to display is 20, we create separate columns by category
"""

def has_usps_implementation(df, implementation_type):
  return df[df['USPS implementation'] == implementation_type]

def not_has_usps_implementation(df, implementation_type):
  return df[df['USPS implementation'] != implementation_type]

def get_USPS_sites_before(df):
  return df[(pd.isnull(df['usps_before_gpc']) == False) ]
def get_USPS_sites_after(df):
  return df[(pd.isnull(df['usps_after_gpc']) == False)]
def get_USPS_sites_values(df, time):
  return (df[(pd.isnull(df['usps_'+time+'_gpc']) == False) & (df['usps_'+time+'_gpc'].str.contains(r'^..[yY].$'))],
          df[(pd.isnull(df['usps_'+time+'_gpc']) == False) & (df['usps_'+time+'_gpc'].str.contains(r'^..[nN].$'))],
          df[(pd.isnull(df['usps_'+time+'_gpc']) == False) & (df['usps_'+time+'_gpc'].str.contains(r'^..-.$'))])

def plot_barh_chart_usps(df, colors, title, save, time):

  # get the data to plot
  opt_out_b, no_opt_out_b, no_gpc_b = get_USPS_sites_values(df,'before')
  opt_out_a, no_opt_out_a, no_gpc_a = get_USPS_sites_values(df,'after')

  # to get total number of sites with OAC, concat all then drop duplicates. This is necessary because # with OAC before and after may be different.
  n_title = len(pd.concat([get_USPS_sites_after(df), get_USPS_sites_before(df)]).drop(columns=[ 'decoded_gpp_before_gpc', 'decoded_gpp_after_gpc', 'unique_ad_networks']).drop_duplicates())

  na, opt_out, not_opt_out = ([len(no_gpc_a), len(no_gpc_b)],
                              [len(opt_out_a), len(opt_out_b)],
                              [len(no_opt_out_a), len(no_opt_out_b)])

  ind = np.arange(2)
  width = 0.6

  fig, ax = plt.subplots(figsize =(8, 2.5), dpi=100)

  # plot the bars
  left = np.zeros(2)
  data = [na, not_opt_out, opt_out]
  i = 0
  for bar in range(len(data)):
    p = ax.barh(ind, data[bar], width, left = left, color=colors[bar])
    left += data[i]
    # ax.bar_label(p, label_type='center', padding=1, fmt='{:,.0f}',fontsize=10.5)
    i += 1

#     ######
#   # set titles/axes/labels
  y_placement = []
  for i in range(len(data)):
    pos1= 0.22 + i
    pos2 = 0.5 + i
    pos3 = i
    y_placement.append([pos1,pos2, pos3])
  data_by_bar = [[i[x] for i in data] for x in range(len(data[0]))]
  n = max([sum(x) for x in data_by_bar])
  ax.set_xlim(right=ax.get_xlim()[1]+(n*.02), auto=False)
  ax.margins(0, .25)
  for month in ind:
    x_placement = []

    for idx in range(len(data_by_bar[month])):
      frac = .08 # if a bar is less than this fraction of total, we want to use an arrow to point and label that way
      if data_by_bar[month][idx] < frac*n:
        label_placement = sum(data_by_bar[month][0:idx]) + 0.35*(data_by_bar[month][idx]) # since the arrows are tilted they're too far right. adjusted this by using .35 instead of.5
        if (len(x_placement) > 0) and (label_placement - x_placement[-1] < .05*n): # if labels are too close, move them over more to the right
          text_placement = label_placement + .05*n
        else:
          text_placement = label_placement
        ax.annotate(format(data_by_bar[month][idx], ',d') , xy=(label_placement, y_placement[month][0]), xytext=(text_placement, y_placement[month][1]), arrowprops=dict(facecolor='black', arrowstyle="->"),fontsize=11)
      else:
        label_placement = sum(data_by_bar[month][0:idx]) + 0.5*(data_by_bar[month][idx]) # put just text labels directly in the middle
        text_placement = label_placement
        ax.annotate(format(data_by_bar[month][idx], ',d'), xy=(label_placement, y_placement[month][2]), ha= 'center', va= 'center',fontsize=11)
#       x_placement += [text_placement]
#   #######
  # set titles/axes
  plt.title(title +' ('+time+', n = '+format (n_title, ',d')+')', pad = 30,fontsize=14)
  ax.set_yticks(ind)
  ax.set_yticklabels(['After GPC', 'Before GPC'],fontsize=11)
  plt.xticks(np.arange(0, na[1]+not_opt_out[1]+opt_out[1] + 125, 250),fontsize=11)
  xlabels = [format(label, ',.0f') for label in ax.get_xticks()] # just add commas
  # xlabels = [format_labels(label) for label in ax.get_xticks()] # axis are 1K, 2K, etc, numbers are too small for this in this graph
  ax.set_xticklabels(xlabels)
  fig.legend(('Not Applicable', 'Did Not Opt Out', 'Opted Out'), ncols=3, bbox_to_anchor=(.81, 1.03),fontsize=10.5)
  if save == True:
    plt.savefig(fig_save_path + time.replace('/', '_').replace(' ', '_') + '_USPS_opt_outs.png', dpi=100, bbox_inches='tight') ###########
  plt.show()

"""Distribution of USPS/GPP/OAC implementations
---
"""

def sites_with_gpp(df):
  return df[(pd.isnull(df['gpp_before_gpc']) == False) | (pd.isnull(df['gpp_after_gpc']) == False)]

def sites_with_OAC(df):
  return df[(pd.isnull(df['OptanonConsent_before_gpc']) == False) | (pd.isnull(df['OptanonConsent_after_gpc']) == False)]

def sites_with_usps(df):
  return df[(pd.isnull(df['usps_before_gpc']) == False) | (pd.isnull(df['usps_after_gpc']) == False)]

# for dealing w/ crawler collected data
# def has_wellknown_any_value(df):
#     df1 = cast_as_string(df, ['wellknown'])
#     return df1[(df1['wellknown'].str.contains('"gpc":'))]

# def has_wellknown(df):
#     # print(df.dtypes)
#     df1 = cast_as_string(df, ['wellknown'])
#     return df1[(df1['wellknown'].str.contains('"gpc":true'))]

def has_wellknown_any_value(df):
    return df[(df['Well-known'].str.contains("'gpc':", na=False)) ]

def has_wellknown(df):
    return df[(df['Well-known'].str.contains("'gpc': True", na=False)) ]

# print("# sites with gpp:", len(sites_with_gpp(added)))
# print("# sites with OptanonConsent cookie:", len(sites_with_OAC(added)))
# print("# sites with usps:", len(sites_with_usps(added)))
def sites_with_nothing(df):
  return df[  ((pd.isnull(df['usps_before_gpc']) == True) & (pd.isnull(df['usps_after_gpc']) == True))
            & ((pd.isnull(df['OptanonConsent_before_gpc']) == True) & (pd.isnull(df['OptanonConsent_after_gpc']) == True))
            & ((pd.isnull(df['gpp_before_gpc']) == True) & (pd.isnull(df['gpp_after_gpc']) == True))]



def sites_with_all3(df):
  return df[  ((pd.isnull(df['usps_before_gpc']) == False) | (pd.isnull(df['usps_after_gpc']) == False))
            & ((pd.isnull(df['OptanonConsent_before_gpc']) == False) | (pd.isnull(df['OptanonConsent_after_gpc']) == False))
            & ((pd.isnull(df['gpp_before_gpc']) == False) | (pd.isnull(df['gpp_after_gpc']) == False))]
# sites_with_all3(added)

def sites_with_OAC_and_USPS_only(df):
  return df[  ((pd.isnull(df['usps_before_gpc']) == False) | (pd.isnull(df['usps_after_gpc']) == False))
            & ((pd.isnull(df['OptanonConsent_before_gpc']) == False) | (pd.isnull(df['OptanonConsent_after_gpc']) == False))
            & ((pd.isnull(df['gpp_before_gpc']) == True) & (pd.isnull(df['gpp_after_gpc']) == True))] # no gpp before and after
def sites_with_OAC_and_GPP_only(df):
  return df[  ((pd.isnull(df['usps_before_gpc']) == True) & (pd.isnull(df['usps_after_gpc']) == True)) # no usps before and after
            & ((pd.isnull(df['OptanonConsent_before_gpc']) == False) | (pd.isnull(df['OptanonConsent_after_gpc']) == False))
            & ((pd.isnull(df['gpp_before_gpc']) == False) | (pd.isnull(df['gpp_after_gpc']) == False))]

def sites_with_USPS_and_GPP_only(df):
  return df[  ((pd.isnull(df['usps_before_gpc']) == False) | (pd.isnull(df['usps_after_gpc']) == False))
            & ((pd.isnull(df['OptanonConsent_before_gpc']) == True) & (pd.isnull(df['OptanonConsent_after_gpc']) == True)) # doesn't have cookie before and after
            & ((pd.isnull(df['gpp_before_gpc']) == False) | (pd.isnull(df['gpp_after_gpc']) == False))]



def sites_with_OAC_only(df):
  return df[  ((pd.isnull(df['usps_before_gpc']) == True) & (pd.isnull(df['usps_after_gpc']) == True)) # no usps before and after
            & ((pd.isnull(df['OptanonConsent_before_gpc']) == False) | (pd.isnull(df['OptanonConsent_after_gpc']) == False))
            & ((pd.isnull(df['gpp_before_gpc']) == True) & (pd.isnull(df['gpp_after_gpc']) == True))] # no gpp before and after

def sites_with_GPP_only(df):
  return df[  ((pd.isnull(df['usps_before_gpc']) == True) & (pd.isnull(df['usps_after_gpc']) == True)) # no usps before and after
            & ((pd.isnull(df['OptanonConsent_before_gpc']) == True) & (pd.isnull(df['OptanonConsent_after_gpc']) == True)) # no optanon before and after
            & ((pd.isnull(df['gpp_before_gpc']) == False) | (pd.isnull(df['gpp_after_gpc']) == False))]


def sites_with_USPS_only(df):
  return df[  ((pd.isnull(df['usps_before_gpc']) == False) | (pd.isnull(df['usps_after_gpc']) == False))
            & ((pd.isnull(df['OptanonConsent_before_gpc']) == True) & (pd.isnull(df['OptanonConsent_after_gpc']) == True)) # doesn't have cookie before and after
            & ((pd.isnull(df['gpp_before_gpc']) == True) & (pd.isnull(df['gpp_after_gpc']) == True))] # no gpp before and after


def compute_USPS_OAC_GPP_distribution(df):
  return (sites_with_USPS_only(df),
  sites_with_GPP_only(df),
  sites_with_USPS_and_GPP_only(df),
  sites_with_OAC_only(df),
  sites_with_OAC_and_USPS_only(df),
  sites_with_OAC_and_GPP_only(df),
  sites_with_all3(df))

def plot_ps_venn(added, time):
  from matplotlib_venn import venn3
  from matplotlib_venn import venn3_unweighted

  fig, ax = plt.subplots(figsize=(3.50, 4.25), dpi=100)

  # 1 only, 2 only, 1&2, 3 only, 1&3, 2&3, 1&2&3
  added = apply_eval(added, ['decoded_gpp_after_gpc', 'decoded_gpp_before_gpc'])
  a, b, c, d, e, f, g = compute_USPS_OAC_GPP_distribution(added)
  venn = venn3(subsets = (len(a), # usps only
                  len(b), # gpp only
                  len(c), # usps & gpp
                  len(d), # optanon only
                  len(e), # usps and optanon
                  len(f), # gpp and optanon
                  len(g)  # all 3
                  ), set_labels = ('USP String', 'GPP String', 'OptanonConsent Cookie')
              #, subset_label_formatter=lambda x: f"{(x/(len(a)+len(b)+len(c)+len(d)+len(e)+len(f)+len(g))):1.0%}"
                          # , subset_label_formatter=lambda x: f"{(x):1.0%}"
                  , subset_label_formatter=lambda x: format(x, ',d')
              )

  # ax.add_patch(venn)
  plt.title("Distribution of Privacy String\nImplementations " +
            "("+time+", n = " +format (len(a)+len(b)+len(c)+len(d)+len(e)+len(f)+len(g), ',d')+")")
  plt.savefig(fig_save_path + time.replace('/', '_').replace(' ', '_') + '_ps_dist.png', dpi=100)
  plt.show()

"""Breaking down which sites are subject to CCPA
------
"""

def ccpa_subjection_privacy_string_breakdown(df, url_string):
  # url_string is defined globally
  # swn = sites_with_nothing(df) # this is for not including well-known
  # this is for including well-known
  # # print(df.columns)
  # swn = df[((pd.isnull(df['usps_before_gpc']) == True) & (pd.isnull(df['usps_after_gpc']) == True)) # USPS
  #           & ((pd.isnull(df['OptanonConsent_before_gpc']) == True) & (pd.isnull(df['OptanonConsent_after_gpc']) == True)) # OAC
  #           & ((pd.isnull(df['gpp_before_gpc']) == True) & (pd.isnull(df['gpp_after_gpc']) == True)) #GPP
  #           & (~df['Well-known'].str.contains("'gpc': True")) ] # this last line must be changed to use wellknown collected by crawler (cast as string first)

  swn = df[((pd.isnull(df['usps_before_gpc']) == True) & (pd.isnull(df['usps_after_gpc']) == True)) # USPS
            & ((pd.isnull(df['OptanonConsent_before_gpc']) == True) & (pd.isnull(df['OptanonConsent_after_gpc']) == True)) # OAC
            & ((pd.isnull(df['gpp_before_gpc']) == True) & (pd.isnull(df['gpp_after_gpc']) == True)) #GPP
            & (~df['Well-known'].str.contains("'gpc'", na=False)) ] # this last line must be changed to use wellknown collected by crawler (cast as string first)
  no_implementation_no_third_party = swn[swn['third_party_count'] == 0] # these are sites that have no integrated SAFG network
  no_implementation_third_party = swn[swn['third_party_count'] != 0] ##########

  no_implementation_know_subject = no_implementation_third_party[no_implementation_third_party['third_party_urls'].str.contains(url_string, na=False)] #these are sites that have an SAFG network we did manually analyze
  no_implementation_may_be_subject = no_implementation_third_party[~no_implementation_third_party['third_party_urls'].str.contains(url_string, na=False)] #these are sites that have an SAFG network we didn't manually analyze.


  # now we want to split up the sites with some implementation into sites we know are subject and sites that may be subject
  sws = pd.concat([df,swn]).drop_duplicates(subset=['Site URL'],keep=False)
  some_implementation_no_third_party = sws[sws['third_party_count'] == 0]

  some_implementation_third_party = sws[sws['third_party_count'] != 0] ###########
  some_implementation_know_subject = some_implementation_third_party[some_implementation_third_party['third_party_urls'].str.contains(url_string, na=False)]
  some_implementation_may_be_subject = some_implementation_third_party[~some_implementation_third_party['third_party_urls'].str.contains(url_string, na=False)]
  return no_implementation_no_third_party, no_implementation_know_subject, no_implementation_may_be_subject, some_implementation_no_third_party, some_implementation_know_subject, some_implementation_may_be_subject

def plot_subject_to_cppa3(df, time, url_string):
  f=11
  no_implementation_no_third_party, no_implementation_know_subject, no_implementation_may_be_subject, some_implementation_no_third_party, some_implementation_know_subject, some_implementation_may_be_subject = ccpa_subjection_privacy_string_breakdown(df, url_string)

  data = [ len(no_implementation_may_be_subject)+ len(some_implementation_may_be_subject),
           len(no_implementation_know_subject)+ len(some_implementation_know_subject),
         len(no_implementation_no_third_party)+ len(some_implementation_no_third_party) ]
  ind = np.arange(1)
  width = 0.45
  fig, ax = plt.subplots(figsize=(8.0, 2.0), dpi=100)
  colors = ["#1780a6", '#a61742','#328545']

  left = np.zeros(1)
  for bar in range(len(data)):
    p = ax.barh(ind, data[bar], width, left = left,color=colors[bar])
    left += data[bar]

  len_data = 0
  for i in data:
    len_data += i
  # set titles/axes
  for idx in range(len(data)):
    frac = .08 # if a bar is less than this fraction of total, we want to use an arrow to point and label that way
    if data[idx] < frac*len_data:
      label_placement = sum(data[0:idx]) + 0.35*(data[idx]) # since the arrows are tilted they're too far right. adjusted this by using .35 instead of.5
      if idx%2 == 0: # make sure arrows aren't right next to each other
        ax.annotate(format(data[idx], ',d'), xy=(label_placement, 0.2), xytext=(label_placement, .36), arrowprops=dict(facecolor='black', arrowstyle="->"),fontsize=f)
      else:
        ax.annotate(format(data[idx], ',d'), xy=(label_placement, -0.2), xytext=(label_placement, -.41), arrowprops=dict(facecolor='black', arrowstyle="->"),fontsize=f)
    else:
      label_placement = sum(data[0:idx]) + 0.5*(data[idx]) # put just text labels directly in the middle
      ax.annotate(format(data[idx], ',d'), xy=(label_placement, 0), ha= 'center', va= 'center',fontsize=f)
  ax.margins(None, .5)
  plt.title('Do Sites in Our Crawl Set Integrate Ad Networks that Sell/Share Data?\n('+time+', n = '+format(len_data, ',d')+")", pad = 42)
  plt.xticks(np.arange(0, len_data, 1000),fontsize=f)
  # xlabels = [format(label, ',.0f') for label in ax.get_xticks()] # numbers just with commas
  xlabels = [format_labels(label) for label in ax.get_xticks()]
  ax.set_xticklabels(xlabels)
  ax.set_yticks(ind)
  ax.set_yticklabels([''])
  fig.legend(('Likely Integration',
              'Verified Integration',
              'No Integration'),
             ncols=3, bbox_to_anchor=(.9, 1.16))
  plt.savefig(fig_save_path + time.replace('/', '_').replace(' ', '_') + '_sell_share_integration.png', dpi=100, bbox_inches='tight')

  plt.show()

# ('Likely: Contains Disconnect Ad Network We Did Not Analyze',
#               'Yes: Contains Disconnect Ad Network We Manually Analyzed',
#               'No: Contains No Ad Networks')

def plot_subject_to_cppa2(df, time, url_string):
  f = 11
  no_implementation_no_third_party, no_implementation_know_subject, no_implementation_may_be_subject, some_implementation_no_third_party, some_implementation_know_subject, some_implementation_may_be_subject = ccpa_subjection_privacy_string_breakdown(df, url_string)

  data = [len(no_implementation_may_be_subject), len(some_implementation_may_be_subject),
           len(no_implementation_know_subject), len(some_implementation_know_subject),
          len(no_implementation_no_third_party),len(some_implementation_no_third_party)]
  ind = np.arange(1)
  width = 0.45
  fig, ax = plt.subplots(figsize=(8.0, 2.0), dpi=100)
  colors = [ "#1780a6",'#5cb2d6','#a61742', '#ad4565','#328545','#6fbd82']   #2091ba

  left = np.zeros(1)
  for bar in range(len(data)):
    p = ax.barh(ind, data[bar], width, left = left,color=colors[bar])
    left += data[bar]

  len_data = 0
  for i in data:
    len_data += i
  # set titles/axes/labels
  ax.margins(None, .5)
  for idx in range(len(data)):
    frac = .08 # if a bar is less than this fraction of total, we want to use an arrow to point and label that way
    if data[idx] < frac*len_data:
      label_placement = sum(data[0:idx]) + 0.35*(data[idx]) # since the arrows are tilted they're too far right. adjusted this by using .35 instead of.5
      if idx%2 == 0: # make sure arrows aren't right next to each other
        ax.annotate(format(data[idx], ',d') , xy=(label_placement, 0.2), xytext=(label_placement, .36), arrowprops=dict(facecolor='black', arrowstyle="->"),fontsize=f)
      else:
        ax.annotate(format(data[idx], ',d'), xy=(label_placement, -0.2), xytext=(label_placement, -.41), arrowprops=dict(facecolor='black', arrowstyle="->"),fontsize=f)
    else:
      label_placement = sum(data[0:idx]) + 0.5*(data[idx]) # put just text labels directly in the middle
      ax.annotate(format(data[idx], ',d'), xy=(label_placement, 0), ha= 'center', va= 'center',fontsize=f)

# Are Sites With or Without Privacy Strings subject to the CCPA?
# Does CCPA subjection impact Privacy String Implementation?
# Integration of Ad Networks that Sell/Share Data and Presence of Privacy Strings
  plt.title('Integration of Ad Networks that Sell/Share Data \nand Presence of Privacy Strings ('+time+', n = '+format(len_data, ',d')+")", pad = 60)
  plt.xticks(np.arange(0, len_data, 1000),fontsize=f)
  # xlabels = [format(label, ',.0f') for label in ax.get_xticks()]
  xlabels = [format_labels(label) for label in ax.get_xticks()]
  ax.set_xticklabels(xlabels)
  ax.set_yticks(ind)
  ax.set_yticklabels([''])
  fig.legend(('Likely Integration, No Privacy String',
              'Likely Integration, Privacy String',
              'Verified Integration, No Privacy String',
              'Verified Integration, Privacy String',
              'No Integration, No Privacy String',
              'No Integration, Privacy String',),
             ncols=2, bbox_to_anchor=(.91, 1.27))

  plt.savefig(fig_save_path + time.replace('/', '_').replace(' ', '_') + '_sell_share_integration_by_ps.png', dpi=100, bbox_inches='tight')

  plt.show()

"""Computing Full Opt Outs
---
"""

def opt_out_usps(df):
  # the site just needs to be opted out after gpc
   return df[(pd.isnull(df['usps_after_gpc']) == False) & (df['usps_after_gpc'].str.contains(r'^..[yY].$'))]
def opt_out_OAC(df):
  # the site just needs to be opted out after gpc
   return df[(pd.isnull(df['OptanonConsent_after_gpc']) == False) & (df['OptanonConsent_after_gpc'] == 'isGpcEnabled=1')]

# def opt_out_gpp(df_gpp):
#   # finds full opt outs (i.e. opts out in all categories for that section)
#   df = sections_table(df_gpp)
#   usnatv1_opt_out = df[(pd.isnull(df['usnatv1_after']) == False) & (df['usnatv1_after'].str.contains(r'^1,1,1,[10]$'))]
#   uscav1_opt_out = df[((pd.isnull(df['uscav1_after']) == False) & (df['uscav1_after'].str.contains(r'^1,1,,[10]$')))]
#   usvav1_opt_out = df[((pd.isnull(df['usvav1_after']) == False) & (df['usvav1_after'].str.contains(r'^1,,1,$')))]
#   uscov1_opt_out = df[((pd.isnull(df['uscov1_after']) == False) & (df['uscov1_after'].str.contains(r'^1,,1,[10]$')))]
#   usutv1_opt_out = df[((pd.isnull(df['usutv1_after']) == False) & (df['usutv1_after'].str.contains(r'^1,,1,$')))]
#   usctv1_opt_out = df[((pd.isnull(df['usctv1_after']) == False) & (df['usctv1_after'].str.contains(r'^1,,1,[10]$')))]
#   concat = pd.concat([usnatv1_opt_out, uscav1_opt_out, usvav1_opt_out, uscov1_opt_out, usutv1_opt_out, usctv1_opt_out]).drop_duplicates(subset=['Site URL'])
#   return concat
def opt_out_gpp(df_gpp):
  # finds full opt outs (i.e. opts out in all categories for that section)
  df = sections_table(df_gpp)
  # order is sale, sharing, targeted advertising, gpc subsection -- we only care about sale and sharing
  usnatv1_opt_out = df[(pd.isnull(df['usnatv1_after']) == False) & (df['usnatv1_after'].str.contains(r'^1,1,[012],[10]$'))]
  uscav1_opt_out = df[((pd.isnull(df['uscav1_after']) == False) & (df['uscav1_after'].str.contains(r'^1,1,,[10]$')))]
  usvav1_opt_out = df[((pd.isnull(df['usvav1_after']) == False) & (df['usvav1_after'].str.contains(r'^1,,[012],$')))]
  uscov1_opt_out = df[((pd.isnull(df['uscov1_after']) == False) & (df['uscov1_after'].str.contains(r'^1,,[012],[10]$')))]
  usutv1_opt_out = df[((pd.isnull(df['usutv1_after']) == False) & (df['usutv1_after'].str.contains(r'^1,,[012],$')))]
  usctv1_opt_out = df[((pd.isnull(df['usctv1_after']) == False) & (df['usctv1_after'].str.contains(r'^1,,[012],[10]$')))]
  concat = pd.concat([usnatv1_opt_out, uscav1_opt_out, usvav1_opt_out, uscov1_opt_out, usutv1_opt_out, usctv1_opt_out]).drop_duplicates(subset=['Site URL'])
  return concat

def intersection(fun1, fun2, df):
  return pd.merge(fun1(df),fun2(df), how='inner', on=['Site URL', 'site_id', 'status', 'domain', 'sent_gpc', 'urlClassification' ])

def no_opt_out_usps(df):
  # the site just needs to be not opted out after gpc. This means the string could be None, or the 3rd char could be - or N
   return df[~((pd.isnull(df['usps_after_gpc']) == False) & (df['usps_after_gpc'].str.contains(r'^..[yY].$'))) ]
def no_opt_out_OAC(df):
  # the site just needs to be opted out after gpc
   return df[~((pd.isnull(df['OptanonConsent_after_gpc']) == False) & (df['OptanonConsent_after_gpc'] == 'isGpcEnabled=1'))]
def no_opt_out_GPP(df_gpp):
  df = sections_table(df_gpp)
  # drop the sites that opt out via gpp from the full table of gpp sites
  return pd.concat([df, opt_out_gpp(df_gpp)]).drop_duplicates(keep=False, subset=['Site URL'])

def usps_gpp_partial(df):
  usps_no_GPP = intersection(opt_out_usps, no_opt_out_GPP, df)
  no_usps_GPP = intersection(no_opt_out_usps, opt_out_gpp, df)
  return usps_no_GPP, no_usps_GPP
def usps_OAC_partial(df):
  usps_no_OAC = intersection(opt_out_usps, no_opt_out_OAC, df)
  no_usps_OAC = intersection(no_opt_out_usps, opt_out_OAC, df)
  return usps_no_OAC, no_usps_OAC
def gpp_OAC_partial(df):
  gpp_no_OAC = intersection(opt_out_gpp, no_opt_out_OAC, df)
  no_gpp_OAC = intersection(no_opt_out_GPP, opt_out_OAC, df)
  return gpp_no_OAC, no_gpp_OAC
def no_opt_out(a,b,c,d,e,f,g):
  # no opt out means site does not opt out via any implemented privacy strings
  a_no_opt_out = no_opt_out_usps(a)
  b_no_opt_out = no_opt_out_GPP(b)
  c_no_opt_out = intersection(no_opt_out_usps,no_opt_out_GPP,c)
  d_no_opt_out = no_opt_out_OAC(d)
  e_no_opt_out = intersection(no_opt_out_usps,no_opt_out_OAC,e)
  f_no_opt_out = intersection(no_opt_out_GPP,no_opt_out_OAC,f)
  g_no_opt_out = no_opt_out_OAC(intersection(no_opt_out_usps,no_opt_out_GPP,g))
  return (a_no_opt_out, b_no_opt_out, c_no_opt_out, d_no_opt_out, e_no_opt_out, f_no_opt_out, g_no_opt_out)
def compute_full_opt_out(a,b,c,d,e,f,g):
  # full opt out means the site opts out via all implemented privacy strings
  a1 = opt_out_usps(a)
  b1 = opt_out_gpp(b)
  c1 = intersection(opt_out_usps,opt_out_gpp,c)
  d1 = opt_out_OAC(d)
  e1 = intersection(opt_out_usps,opt_out_OAC,e)
  f1 = intersection(opt_out_gpp,opt_out_OAC,f)
  g1 = opt_out_OAC(intersection(opt_out_usps,opt_out_gpp,g))
  return (a1, b1, c1, d1, e1, f1, g1)

def compute_partial_opt_outs(a,b,c,d,e,f,g):
  # site must have 2 or more privacy strings in order for this to occur
  # case of 2 privacy strings
  usps_no_GPP, no_usps_GPP = usps_gpp_partial(c) # when site has usps and gpp only
  usps_no_OAC, no_usps_OAC = usps_OAC_partial(e) # when site has usps and oac only
  gpp_no_OAC, no_gpp_OAC = gpp_OAC_partial(f) # when site has gpp and oac only
  # case of 3 privacy strings
  # OAC, USPS, GPP
  #  Y.   N.   N
  oac_nousps_nogpp = no_opt_out_usps(intersection(no_opt_out_GPP, opt_out_OAC, g))
  #  Y.   Y.   N
  oac_usps_nogpp = opt_out_usps(intersection(no_opt_out_GPP, opt_out_OAC, g))
  #  Y.   N.   Y
  oac_nousps_gpp = no_opt_out_usps(intersection(opt_out_gpp, opt_out_OAC, g))
  #  N.   N.   Y
  nooac_nousps_gpp = no_opt_out_usps(intersection(opt_out_gpp, no_opt_out_OAC, g))
  #  N.   Y.   N
  nooac_usps_nogpp = opt_out_usps(intersection(no_opt_out_GPP, no_opt_out_OAC, g))
  #  N.   Y.   Y
  nooac_usps_gpp = opt_out_usps(intersection(opt_out_gpp, no_opt_out_OAC, g))


  return usps_no_GPP, no_usps_GPP, usps_no_OAC, no_usps_OAC, gpp_no_OAC, no_gpp_OAC, oac_nousps_nogpp, oac_usps_nogpp, oac_nousps_gpp, nooac_nousps_gpp, nooac_usps_nogpp,  nooac_usps_gpp

"""bar chart with # sites per grade

1. full opt out: sum(a1 to g1)
2. partial opt out: must have > thing implemented; only look at the intersection (c,e,f,g)
3. no opt out
4. nothing implemented: sites_with_nothing(df)
"""

def plot_grading(df, time):
  a, b, c, d, e, f, g = compute_USPS_OAC_GPP_distribution(df)
  a1, b1, c1, d1, e1, f1, g1 = compute_full_opt_out(a,b,c,d,e,f,g)
  a2, b2, c2, d2, e2, f2, g2 = no_opt_out(a,b,c,d,e,f,g)
  usps_no_GPP, no_usps_GPP, usps_no_OAC, no_usps_OAC, gpp_no_OAC, no_gpp_OAC, oac_nousps_nogpp, oac_usps_nogpp, oac_nousps_gpp, nooac_nousps_gpp, nooac_usps_nogpp, nooac_usps_gpp = compute_partial_opt_outs(a,b,c,d,e,f,g)
  print('len of input df:', len(df))
  print("number sites with no USPS, GPP, or OAC:", len(sites_with_nothing(df)))
  data = [
          len(a1)+len(b1)+len(c1)+len(d1)+len(e1)+len(f1)+len(g1), # full opt out
          len(usps_no_GPP)+len(no_usps_GPP)+len(usps_no_OAC)+len(no_usps_OAC)+len(gpp_no_OAC)+len(no_gpp_OAC)+len(oac_nousps_nogpp)+len(oac_usps_nogpp)+len(oac_nousps_gpp)+len(nooac_nousps_gpp)+len(nooac_usps_nogpp)+len(nooac_usps_gpp), # partial opt out
          len(a2)+len(b2)+len(c2)+len(d2)+len(e2)+len(f2)+len(g2), # no opt out
          len(sites_with_nothing(df))]
  ind = np.arange(1)
  width = 0.6

  fig, ax = plt.subplots(figsize =(8, 2))
  colors = ["#D0BFF5","#A5EC8A","#8ACEEC","#f5a442"]
  # colors = ["#D0BFF5","#B1E0EE","#C2EEB1"]

  left = np.zeros(1)
  for bar in range(len(data)):
    p = ax.barh(ind, data[bar], width, left = left,color=colors[bar])
    left += data[bar]
    ax.bar_label(p, label_type='center', fmt='{:,.0f}')

  len_data = 0
  for i in data:
    len_data += i
  # set titles/axes
  ax.margins(None, .5)
  plt.title('Distribution of Sites by Rating ('+time+', n = '+format (len_data, ',d')+")", pad = 30)
  plt.xticks(np.arange(0, len_data, 1000))
  # xlabels = [format(label, ',.0f') for label in ax.get_xticks()]
  xlabels = [format_labels(label) for label in ax.get_xticks()]
  ax.set_xticklabels(xlabels)
  ax.set_yticks(ind)
  ax.set_yticklabels([''])
  fig.legend(('Full Opt Out','Partial Opt Out',"No Opt Out",'None'), ncols=4, bbox_to_anchor=(.895, 1.07))
  # plt.show()

"""Plotting functions
---
"""

def plot_barh_chart_4(table, labels, col_list, colors, title, time):
  # plot a bar chart w/ 4 bars: input the df, the bar labels,
  # the function that gets the data to plot from the df, the color of the bars
  # and the title of the graph

  # get the data to plot
  pos, neg = get_fig_data(col_list, table)

  ind = np.arange(4)
  width = 0.5

  fig, ax = plt.subplots(figsize =(8, 4))

  # plot the bars
  left = np.zeros(4)
  data = [pos,neg]
  for bar in range(len(data)):
    p = ax.barh(ind, data[bar], width, left = left, color=colors[bar])
    left += pos
    ax.bar_label(p, label_type='center', padding=5, fmt='{:,.0f}')

  # set titles/axes
  plt.title(title +' ('+time+', n = '+format(pos[0]+neg[0], ',d')+')', pad = 30)
  ax.set_yticks(ind)
  ax.set_yticklabels(labels)
  plt.xticks(np.arange(0, pos[0]+neg[0], 1000))
  # xlabels = [format(label, ',.0f') for label in ax.get_xticks()]
  xlabels = [format_labels(label) for label in ax.get_xticks()]
  ax.set_xticklabels(xlabels)
  fig.legend(('Positive Instances Count','Negative Instances Count'), ncols=2, bbox_to_anchor=(.81, .97))
  plt.show()

def plot_barh_chart_3(table, labels, col_list, colors, title, time):
  # plot a bar chart w/ 4 bars: input the df, the bar labels,
  # the function that gets the data to plot from the df, the color of the bars
  # and the title of the graph

  # get the data to plot
  pos, neg = get_fig_data(col_list, table)

  ind = np.arange(3)
  width = 0.5

  fig, ax = plt.subplots(figsize =(8, 4))

  # plot the bars
  left = np.zeros(3)
  data = [pos,neg]
  for bar in range(len(data)):
    p = ax.barh(ind, data[bar], width, left = left, color=colors[bar])
    left += pos
    ax.bar_label(p, label_type='center', padding=5, fmt='{:,.0f}')

  # set titles/axes
  plt.title(title +' ('+time+', n = '+format(pos[0]+neg[0], ',d')+')', pad = 30)
  ax.set_yticks(ind)
  ax.set_yticklabels(labels)
  plt.xticks(np.arange(0, pos[0]+neg[0], 1000))
  # xlabels = [format(label, ',.0f') for label in ax.get_xticks()]
  xlabels = [format_labels(label) for label in ax.get_xticks()]
  ax.set_xticklabels(xlabels)
  fig.legend(('Positive Instances Count','Negative Instances Count'), ncols=2, bbox_to_anchor=(.81, .97))
  plt.show()

def get_fig_data(col_list, table):
  pos = []
  neg = []
  for col in col_list:
    pos.append(list(table[col])[0])
    neg.append(list(table[col])[1])
  return pos, neg

def plot_ps_dist(full_merged_df, df, url_string, time):
    no_implementation_no_third_party, no_implementation_know_subject, no_implementation_may_be_subject, \
    some_implementation_no_third_party, some_implementation_know_subject, some_implementation_may_be_subject = ccpa_subjection_privacy_string_breakdown(df, url_string)

    # ✅ Only change: label list must have *three* entries
    l = ['Ad Network, No PS', 'Ad Network, PS', 'No Ad Network']

    fig, ax = plt.subplots(figsize =(5, 5))
    bins = [0,1500,3000,4500,6000,7500,9000,10500,11700]

    bin_size = []
    x_labels = []
    n = len(full_merged_df)

    for b_id in range(len(bins)-1):
        left_index = min(bins[b_id], n-1)
        right_index = min(bins[b_id+1], n-1)
        bin_size.append(right_index - left_index)
        x_labels.append(
            format(full_merged_df.iloc[left_index]['Tranco'], ',.0f')
            + ' -\n' +
            format(full_merged_df.iloc[right_index]['Tranco'], ',.0f')
        )

    bin_size = np.array(bin_size, dtype='float32')

    n_i = pd.concat([no_implementation_know_subject['site_id'], no_implementation_may_be_subject['site_id']])
    s_i = pd.concat([some_implementation_know_subject['site_id'],some_implementation_may_be_subject['site_id']])
    not_subject = pd.concat([no_implementation_no_third_party['site_id'],some_implementation_no_third_party['site_id']])

    binned_data = plt.hist((n_i, s_i, not_subject), label=l,
                           edgecolor='black', bins=bins,
                           stacked=True, alpha=.4)

    plt.close()  # don't show the histogram

    hist_data = {
        "No PS": binned_data[0][0],
        "PS": binned_data[0][1] - binned_data[0][0],
        "No Ad Network": binned_data[0][2] - binned_data[0][1]
    }

    print(hist_data)

    percents = {}
    for key in hist_data.keys():
        p0 = []
        for i in range(len(hist_data[key])):
            p0.append(hist_data[key][i] / (bins[i+1]-bins[i]) * 100)
        percents[key] = np.array(p0)

    width = 1
    print(percents)

    fig, ax = plt.subplots()
    bottom = np.zeros(len(bins)-1)

    colors = ['red', 'lime', 'yellow']

    for boolean, percent in percents.items():
        p = ax.bar(x_labels, percent, width, label=boolean, bottom=bottom)
        bottom += percent

    for x_tick_loc in range(len(bins)):
        plt.vlines(x_tick_loc - .5, 0, 100, colors='#d5d8de', linewidth = 1, alpha=.6)
        plt.vlines(x_tick_loc - .5, -2, 2.4, colors='black', linewidth = 1)
        idx = min(bins[x_tick_loc], len(full_merged_df)-1)

        plt.annotate(
          format_labels(full_merged_df.iloc[idx]['Tranco']),
          (x_tick_loc - .5, -5),
          verticalalignment='top',
          horizontalalignment='center',
          rotation=20,
          fontsize=10.5,
          color='black'
        )

    plt.hlines(0, -.5, 7.5, colors='black', linewidth = 1)

    ax.margins(.07, .15)
    ax.set_title("Distribution of Privacy Strings Over Crawl Set ("+time+")")
    ax.legend(loc="upper right", ncols=3, fontsize=10.5)
    plt.xlabel('Approximate Tranco Rank', fontsize=fontsize)
    plt.xticks([])
    plt.yticks(fontsize=10.5)
    plt.ylabel('Percent',fontsize=fontsize)
    plt.savefig(fig_save_path + time.replace('/', '_').replace(' ', '_') + '_dist_of_ps.png', dpi=100, bbox_inches='tight')

    plt.show()

    return hist_data

#ADDED BY AMBROSE MAY NEED TO DELETE
# -------------------------------------------------------------------
# New helpers for summarising and plotting FULL opt‑outs
# -------------------------------------------------------------------

def create_opt_outs_table(df):
    """
    Build a one‑row‑per‑mechanism summary of sites that **fully** opt out via
    each privacy mechanism (USP String, GPP String, OptanonConsent cookie).

    Parameters
    ----------
    df : pandas.DataFrame
        Filtered crawl dataframe.  Must contain the columns produced by
        `compute_USPS_OAC_GPP_distribution`, including a unique ``site_id``.

    Returns
    -------
    pandas.DataFrame
        Columns:
        * ``Mechanism`` – The name of the privacy mechanism.
        * ``Count``     – Number of distinct sites that fully opt out via it.
    """
    # Split into the 7 mutually‑exclusive buckets expected by the existing
    # helper utilities.
    a, b, c, d, e, f, g = compute_USPS_OAC_GPP_distribution(df)

    # Grab the FULL‑opt‑out subsets for each bucket.
    a1, b1, c1, d1, e1, f1, g1 = compute_full_opt_out(a, b, c, d, e, f, g)

    # Utility to count unique site identifiers across several dataframes.
    def _count_unique(dfs):
        ids = set()
        for _df in dfs:
            if 'site_id' in _df.columns:
                ids.update(_df['site_id'].tolist())
            else:
                # Fallback: use URL if ``site_id`` is absent.
                ids.update(_df['Site URL'].tolist())
        return len(ids)

    counts = {
        'USP String':      _count_unique([a1, c1, e1, g1]),
        'GPP String':      _count_unique([b1, c1, f1, g1]),
        'OptanonConsent':  _count_unique([d1, e1, f1, g1]),
    }

    return pd.DataFrame({'Mechanism': list(counts.keys()),
                         'Count': list(counts.values())})


def plot_opt_outs(opt_outs_table, save, time, colors):
    """
    Bar‑chart visualisation for the dataframe produced by
    :pyfunc:`create_opt_outs_table`.

    Parameters
    ----------
    opt_outs_table : pandas.DataFrame
    save           : bool
        If *True*, the figure is written to ``fig_save_path`` with a
        ``full_opt_outs_<time>.png`` name.
    time           : str
        Crawl label (e.g. ``'Dec2023'``).  Used in the title and filename.
    colors         : list[str]
        A list of three colour strings matching the mechanisms’ order.
    """
    fig, ax = plt.subplots(figsize=(6, 4))

    bars = ax.bar(opt_outs_table['Mechanism'],
                  opt_outs_table['Count'],
                  width=0.6,
                  color=colors[:len(opt_outs_table)])

    # Annotate bars
    for bar in bars:
        height = bar.get_height()
        ax.annotate(f'{height:,}',
                    xy=(bar.get_x() + bar.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center',
                    va='bottom',
                    fontsize=10)

    ax.set_ylabel('# Sites with FULL opt‑out', fontsize=11)
    ax.set_title(f'Full Opt‑Outs by Mechanism ({time})', fontsize=13)
    ax.margins(x=0.05)

    if save:
        fig.savefig(f"{fig_save_path}full_opt_outs_{time}.png",
                    dpi=100,
                    bbox_inches='tight')

    plt.show()
    return fig, ax